version: "3"

services:
  app:
    container_name: app
    build: ./
    command: ["./bin/app"]
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_NAME=assigment
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - SERVER_HOST=0.0.0.0
      - HTTP_PORT=8080
    depends_on:
      - database

  database:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=assigment
    ports:
      - "5060:5432"
